import {END} from 'redux-saga'
import {wrapper} from '../redux/store'
import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  )
}

export const getStaticProps = wrapper.getStaticProps(({store}) => {
  store.dispatch(END)
})
